services:
  web:
    build: .
    container_name: car4sure
    ports:
      - "8000:8080"
    volumes:
      - .:/var/www/html
    environment:
      - APP_KEY=base64:SUQdN9Zsrx5Vni1gzV2rPfMVsOjdzv3drSz5og47uwA=
      - APP_ENV=production
      - APP_URL=https://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/database/database.sqlite
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=info
      - LOG_STDERR_FORMATTER=Monolog\Formatter\JsonFormatter
      - SESSION_SECURE_COOKIE=true
      - APP_NAME=Car4Sure
      - APP_TIMEZONE="Indian/Mauritius"
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_MAINTENANCE_DRIVER=file
      - APP_MAINTENANCE_STORE=database
      - BCRYPT_ROUNDS=12
      - CACHE_STORE=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_CACHE_DB=0
      - REDIS_URL=redis://default:6f09a8a0d53f43528daa7f7e493c6367@redis:6379
      - QUEUE_CONNECTION=redis
      - SCOUT_DRIVER=tntsearch
      - GOTENBERG_URL='http://gotenberg:3000'
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: car4sure-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=6f09a8a0d53f43528daa7f7e493c6367
    networks:
      - internal

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - 3000:3000
    networks:
      - internal

networks:
  internal:
