# fly.toml app configuration file generated for iplatform on 2024-03-15T13:45:23+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iplatform'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '20'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://iplatform.fly.dev'
  DB_CONNECTION = 'sqlite'
  DB_DATABASE = '/var/www/html/storage/database/database.sqlite'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_SECURE_COOKIE = 'true'
  APP_NAME = 'Car4Sure'
  APP_TIMEZONE = "Indian/Mauritius"
  APP_LOCALE = 'en'
  APP_FALLBACK_LOCALE = 'en'
  APP_MAINTENANCE_DRIVER='file'
  APP_MAINTENANCE_STORE='database'
  BCRYPT_ROUNDS = '12'
  CACHE_STORE = 'redis'
  CACHE_DRIVER = 'redis'
  SESSION_DRIVER = 'redis'
  REDIS_CACHE_DB = '0'
  REDIS_URL = 'redis://default:6f09a8a0d53f43528daa7f7e493c6367@fly-ancient-dawn-4060.upstash.io:6379'
  QUEUE_CONNECTION = 'redis'
  SCOUT_DRIVER='tntsearch'
  GOTENBERG_URL='https://demo.gotenberg.dev'

[mounts]
  source = 'storage_vol'
  destination = '/var/www/html/storage'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'


# [processes]
#   app = ""
#   cron = "cron -f"

